DROP TABLE IF EXISTS enrolled;

DROP TABLE IF EXISTS prerequisite;

DROP TABLE IF EXISTS review;

DROP TABLE IF EXISTS course_prereqs;

DROP TABLE IF EXISTS course;

DROP TABLE IF EXISTS instructor;

DROP TABLE IF EXISTS student;
